# Use the official Nginx image as a base
FROM nginx:alpine

# Copy the frontend files to the default Nginx html directory
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Nginx runs automatically
